#!/usr/bin/env python3
"""Pack fixed 16 KiB resource pages with the Kode-compatible Hrust tool."""

from __future__ import annotations

import os
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "build" / "generated" / "weather_assets"
TOOLS = ROOT / "tools" / "hrust"


def tool() -> list[str]:
    if sys.platform == "darwin":
        return [str(TOOLS / "mhmt"), "-hst", "-zxh"]
    if os.name == "nt":
        return [str(TOOLS / "hrust.exe")]
    raise SystemExit("Hrust packer is bundled for macOS and Windows; add a Linux packer before building there")


def main() -> int:
    packed_sizes: list[int] = []
    for index in range(5):
        source = ASSETS / f"page{index:02d}.bin"
        target = ASSETS / f"page{index:02d}.hst"
        if sys.platform == "darwin":
            subprocess.run(tool() + [str(source), str(target)], check=True)
        else:
            subprocess.run(tool() + [str(target), str(source)], check=True)
        if target.stat().st_size > 16 * 1024:
            raise SystemExit(f"{target.name}: packed page exceeds one staging page")
        packed_sizes.append(target.stat().st_size)
    packed_total = sum(packed_sizes)
    if packed_total > 16 * 1024:
        raise SystemExit(
            f"packed resource tail is {packed_total} bytes; it must fit one DSS page"
        )
    (ASSETS / "hrust_sizes.inc").write_text(
        "; generated by tools/pack_hrust.py\n"
        f"GRAPHICS_PACKED_TOTAL EQU {packed_total}\n"
        "GRAPHICS_PACKED_SIZES:\n        DW      "
        + ", ".join(str(size) for size in packed_sizes)
        + "\n",
        encoding="ascii",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
